# Site configuration
remote_theme: wet-boew/gcweb-jekyll
title: "Serice Canada - Principal Publisher | Ã‰diteur principal" # Site name or title

# Collections

# Jekyll collections settings

# Site settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE*
- SECURITY.md
- CNAME
- "*.tmp"
- Gemfile
- Gemfile.lock
- gcweb-jekyll.gemspec
- .jekyll-cache
- node_modules
- vendor/
